(()=>{'use strict';
const $=id=>document.getElementById(id),num=v=>{v=parseFloat(String(v??'').replace(',','.'));return Number.isFinite(v)?v:0},fmt=(v,d=1)=>num(v).toLocaleString('es-CL',{minimumFractionDigits:d,maximumFractionDigits:d}),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),uid=()=>`p${Date.now().toString(36)}${Math.random().toString(36).slice(2,6)}`;
const KEY='orion_aesthetic_procedure_v145',PKEY='orion_documento_paciente_activo_v1';
const Z={
 forehead:['Frente','#f2ad25',[50,15]],glabella:['Glabela / corrugadores','#e98b16',[50,25]],periocular_r:['Periocular derecho','#24a6a1',[21,33]],periocular_l:['Periocular izquierdo','#24a6a1',[79,33]],bunny:['Bunny lines / nasal','#6c4ab6',[50,43]],smile:['Sonrisa gingival / perioral','#df4f91',[50,57]],dao_r:['DAO derecho','#e95d32',[35,64]],dao_l:['DAO izquierdo','#e95d32',[65,64]],menton:['Mentón','#2558a6',[50,70]],masseter_r:['Masetero derecho','#53a44a',[19,60]],masseter_l:['Masetero izquierdo','#53a44a',[81,60]],platysma:['Platisma','#51469a',[50,84]]};
const mk=(z,xy,names)=>xy.map((p,i)=>({id:uid(),zone:z,x:p[0],y:p[1],label:names?.[i]||`${Z[z][0]} ${i+1}`,planned:0,administered:0,status:'suggested',comment:'',source:'preset'}));
const presets=()=>[
 ...mk('forehead',[[34,20],[42,18.5],[50,18],[58,18.5],[66,20]],['Frontal lateral derecho','Frontal paramediano derecho','Frontal central','Frontal paramediano izquierdo','Frontal lateral izquierdo']),
 ...mk('glabella',[[50,28],[43,31],[57,31],[45.5,34],[54.5,34]],['Prócer','Corrugador derecho medial','Corrugador izquierdo medial','Corrugador derecho lateral','Corrugador izquierdo lateral']),
 ...mk('periocular_r',[[24,37],[21.5,41],[23.5,45]]),...mk('periocular_l',[[76,37],[78.5,41],[76.5,45]]),...mk('bunny',[[46.5,47],[53.5,47]]),...mk('smile',[[45.5,59.5],[54.5,59.5]]),...mk('dao_r',[[39,65]]),...mk('dao_l',[[61,65]]),...mk('menton',[[46.5,72],[53.5,72]]),...mk('masseter_r',[[22.5,64],[21.5,69],[20.5,74]]),...mk('masseter_l',[[77.5,64],[78.5,69],[79.5,74]]),...mk('platysma',[[37,87],[43.5,89],[50,90],[56.5,89],[63,87]])];
let S={patient:{name:'',id:'',date:new Date().toISOString().slice(0,10)},vial:{product:'Toxina botulínica tipo A',units:100,dilution:2.5,batch:''},points:presets(),selectedPointId:null,selectedZone:'glabella',visibleZone:null,showLabels:true,zoom:1,addMode:false,mobileTab:'map'};
const zp=(z=S.selectedZone)=>S.points.filter(p=>p.zone===z),sp=()=>S.points.find(p=>p.id===S.selectedPointId),active=()=>S.points.filter(p=>p.status!=='suggested'||num(p.planned)||num(p.administered)||p.comment),calc=()=>{let u=Math.max(0,num(S.vial.units)),d=Math.max(.001,num(S.vial.dilution)),c=u/d,p=S.points.reduce((a,x)=>a+num(x.planned),0),a=S.points.reduce((b,x)=>b+num(x.administered),0);return{u,d,c,p,a,v:c?a/c:0,r:Math.max(0,u-a)}};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),status=s=>({suggested:'Sugerido',planned:'Planificado',administered:'Administrado',omitted:'Omitido'})[s]||s;
function patientMini(){$('patientMiniName').textContent=S.patient.name||'Sin paciente activo';$('patientMiniId').textContent=`RUN/RUT: ${S.patient.id||'—'}`;$('patientMiniDate').textContent=`Fecha: ${S.patient.date||'—'}`}
function zoneControls(){let o=Object.entries(Z).map(([k,z])=>`<option value="${k}">${z[0]}</option>`).join('');$('zoneSelect').innerHTML=o;$('mobileZoneSelect').innerHTML=`<option value="all">Todas las zonas</option>${o}`;$('zoneSelect').value=S.selectedZone;$('mobileZoneSelect').value=S.visibleZone||'all'}
function zoneList(){$('zoneList').innerHTML=Object.entries(Z).map(([k,z])=>`<button type="button" class="oa-zone-button ${S.visibleZone===k?'active':''}" data-zone="${k}"><i class="oa-zone-dot" style="background:${z[1]}"></i><strong>${z[0]}</strong><span>${zp(k).length}</span></button>`).join('');$('zoneList').querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>focusZone(b.dataset.zone,true))}
function labels(){let l=$('zoneLabelLayer');l.innerHTML='';if(!S.showLabels)return;Object.entries(Z).forEach(([k,z])=>{if(S.visibleZone&&S.visibleZone!==k)return;let e=document.createElement('span');e.className='oa-zone-label';e.textContent=z[0];e.style.left=z[2][0]+'%';e.style.top=z[2][1]+'%';l.append(e)})}
function points(){let l=$('pointLayer');l.innerHTML='';S.points.forEach(p=>{let b=document.createElement('button'),z=Z[p.zone];b.type='button';b.className=`oa-point ${p.status}${p.id===S.selectedPointId?' selected':''}${S.visibleZone&&S.visibleZone!==p.zone?' hidden-zone':''}`;b.textContent=zp(p.zone).indexOf(p)+1;b.style.left=p.x+'%';b.style.top=p.y+'%';b.title=`${p.label} · ${status(p.status)}`;if(p.status==='suggested')b.style.boxShadow=`0 0 0 2px ${z[1]},0 2px 6px rgba(0,0,0,.25)`;drag(b,p);l.append(b)});$('mapVisibleCount').textContent=S.points.filter(p=>!S.visibleZone||p.zone===S.visibleZone).length}
function drag(b,p){let moved=false,sx=0,sy=0;b.onpointerdown=e=>{e.preventDefault();e.stopPropagation();select(p.id,false);sx=e.clientX;sy=e.clientY;b.setPointerCapture?.(e.pointerId);b.onpointermove=m=>{if(Math.hypot(m.clientX-sx,m.clientY-sy)>3)moved=true;if(!moved)return;let r=$('pointLayer').getBoundingClientRect();p.x=clamp((m.clientX-r.left)/r.width*100,1.5,98.5);p.y=clamp((m.clientY-r.top)/r.height*100,1.5,98.5);b.style.left=p.x+'%';b.style.top=p.y+'%'};b.onpointerup=u=>{b.releasePointerCapture?.(u.pointerId);b.onpointermove=b.onpointerup=null;if(moved){save();table();toast('Posición actualizada.')}moved=false}};b.onclick=e=>{e.stopPropagation();if(!moved)select(p.id,true)}}
function editor(){let p=sp();$('emptyPoint').hidden=!!p;$('pointFields').hidden=!p;if(!p)return;$('pointLabel').value=p.label;$('pointPlanned').value=p.planned||'';$('pointAdmin').value=p.administered||'';$('pointStatus').value=p.status;$('pointComment').value=p.comment||''}
function summaries(){let c=calc(),q=zp(),p=q.reduce((a,x)=>a+num(x.planned),0),a=q.reduce((b,x)=>b+num(x.administered),0),v=c.c?a/c.c:0;$('zonePlanned').textContent=fmt(p)+' U';$('zoneAdmin').textContent=fmt(a)+' U';$('zoneVolume').textContent=fmt(v,3)+' mL';$('zonePlannedPoints').textContent=q.filter(x=>num(x.planned)).length+' puntos';$('zoneAdminPoints').textContent=q.filter(x=>num(x.administered)).length+' puntos';$('zoneConcentration').textContent=fmt(c.c)+' U/mL';$('concentration').textContent=fmt(c.c)+' U/mL';$('unitsPer01').textContent=fmt(c.c*.1)+' U';$('volumePerUnit').textContent=fmt(c.c?1/c.c:0,3)+' mL';$('remainingUnits').textContent=fmt(c.r)+' U';$('totalPoints').textContent=active().length;$('totalPlanned').textContent=fmt(c.p)+' U';$('totalAdmin').textContent=fmt(c.a)+' U';$('totalVolume').textContent=fmt(c.v,3)+' mL'}
function table(){let c=calc(),r=active(),t=$('pointsTableBody');if(!r.length){t.innerHTML='<tr><td colspan="7" style="padding:18px;text-align:center;color:#70849a">Selecciona un punto y registra unidades o estado.</td></tr>';return}t.innerHTML=r.map(p=>`<tr data-id="${p.id}" class="${p.id===S.selectedPointId?'selected':''}"><td>${Z[p.zone][0]}</td><td>${zp(p.zone).indexOf(p)+1}</td><td>${esc(p.label)}</td><td>${fmt(p.planned)} U</td><td>${fmt(p.administered)} U</td><td>${fmt(c.c?num(p.administered)/c.c:0,3)} mL</td><td><span class="oa-state-pill ${p.status}"><i></i>${status(p.status)}</span></td></tr>`).join('');t.querySelectorAll('[data-id]').forEach(r=>r.onclick=()=>select(r.dataset.id,true))}
function render(){patientMini();zoneList();labels();points();editor();summaries();table();$('zoneSelect').value=S.selectedZone;$('mobileZoneSelect').value=S.visibleZone||'all';$('atlasTransform').style.transform=`scale(${S.zoom})`;$('btnToggleLabels').textContent=S.showLabels?'Ocultar etiquetas':'Mostrar etiquetas'}
function focusZone(z,map=false){if(!Z[z])return;S.selectedZone=z;S.visibleZone=z;render();if(map&&matchMedia('(max-width:920px)').matches)mobile('map')}
function select(id,tab){let p=S.points.find(x=>x.id===id);if(!p)return;S.selectedPointId=id;S.selectedZone=p.zone;render();if(tab&&matchMedia('(max-width:920px)').matches)mobile('record')}
function update(patch){let p=sp();if(!p)return;Object.assign(p,patch);if('planned'in patch||'administered'in patch)p.status=p.status==='omitted'?'omitted':num(p.administered)?'administered':num(p.planned)?'planned':'suggested';render();save()}
function save(notify=false){S.patient={name:$('patientName').value.trim(),id:$('patientId').value.trim(),date:$('procedureDate').value};S.vial={product:$('productName').value.trim(),units:num($('vialUnits').value),dilution:num($('dilutionMl').value),batch:$('batchNumber').value.trim()};try{sessionStorage.setItem(KEY,JSON.stringify(S));if(notify)toast('Registro guardado en esta sesión.')}catch(_){if(notify)toast('No fue posible guardar.')}patientMini()}
function restore(){try{let x=JSON.parse(sessionStorage.getItem(KEY)||'null');if(x&&Array.isArray(x.points))S={...S,...x,addMode:false}}catch(_){}}
function patient(p){p=p?.payload||p;if(!p)return;let n=String(p.nombre||p.nombreCompleto||p.paciente||'').trim(),id=String(p.rut||p.run||'').trim();if(!n&&!id)return;S.patient.name=n;S.patient.id=id;$('patientName').value=n;$('patientId').value=id;save();render()}
function requestPatient(){try{patient(JSON.parse(sessionStorage.getItem(PKEY)||'null'))}catch(_){}if(parent!==window){let o=location.origin==='null'?'*':location.origin;parent.postMessage({type:'ORION_GET_DOCUMENTO_PACIENTE'},o);parent.postMessage({type:'ORION_GET_RECETA_PACIENTE'},o)}}
function toast(m){let t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2400)}
function mobile(t){S.mobileTab=t;document.body.dataset.mobileTab=t;document.querySelectorAll('[data-mobile-tab]').forEach(b=>b.classList.toggle('active',b.dataset.mobileTab===t));scrollTo({top:0,behavior:'smooth'})}
restore();zoneControls();$('atlasImage').src=window.ORION_ANATOMY_ATLAS_FEMALE||'';$('patientName').value=S.patient.name;$('patientId').value=S.patient.id;$('procedureDate').value=S.patient.date;$('productName').value=S.vial.product;$('vialUnits').value=S.vial.units;$('dilutionMl').value=S.vial.dilution;$('batchNumber').value=S.vial.batch;
$('zoneSelect').onchange=e=>focusZone(e.target.value);$('mobileZoneSelect').onchange=e=>{S.visibleZone=e.target.value==='all'?null:e.target.value;if(S.visibleZone)S.selectedZone=S.visibleZone;render()};$('btnFocusZone').onclick=()=>focusZone($('zoneSelect').value,true);$('btnShowAll').onclick=()=>{S.visibleZone=null;render()};$('btnToggleLabels').onclick=()=>{S.showLabels=!S.showLabels;render()};$('btnZoomIn').onclick=()=>{S.zoom=clamp(S.zoom+.1,.8,1.6);render()};$('btnZoomOut').onclick=()=>{S.zoom=clamp(S.zoom-.1,.8,1.6);render()};$('btnFit').onclick=()=>{S.zoom=1;render()};
$('btnAddPoint').onclick=()=>{S.addMode=!S.addMode;$('atlasShell').classList.toggle('add-mode',S.addMode)};$('atlasShell').onclick=e=>{if(!S.addMode||e.target.closest('.oa-point'))return;let r=$('pointLayer').getBoundingClientRect(),z=S.selectedZone,p={id:uid(),zone:z,x:clamp((e.clientX-r.left)/r.width*100,1.5,98.5),y:clamp((e.clientY-r.top)/r.height*100,1.5,98.5),label:`${Z[z][0]} ${zp(z).length+1}`,planned:0,administered:0,status:'suggested',comment:'',source:'custom'};S.points.push(p);S.addMode=false;$('atlasShell').classList.remove('add-mode');select(p.id,true);save();toast('Punto agregado.')};
$('btnResetPresets').onclick=()=>{if(confirm('¿Restablecer presets y eliminar el registro de puntos actual?')){S.points=presets();S.selectedPointId=null;S.visibleZone=null;render();save()}};$('pointLabel').oninput=e=>update({label:e.target.value});$('pointPlanned').oninput=e=>update({planned:Math.max(0,num(e.target.value))});$('pointAdmin').oninput=e=>update({administered:Math.max(0,num(e.target.value))});$('pointStatus').onchange=e=>update({status:e.target.value});$('pointComment').oninput=e=>update({comment:e.target.value});$('btnMarkAdmin').onclick=()=>{let p=sp();if(p)update({administered:num(p.planned),status:'administered'})};$('btnDeletePoint').onclick=()=>{let p=sp();if(p&&confirm(`¿Eliminar ${p.label}?`)){S.points=S.points.filter(x=>x.id!==p.id);S.selectedPointId=null;render();save()}};
$('btnApplyZone').onclick=()=>{let p=Math.max(0,num($('bulkPlan').value)),a=Math.max(0,num($('bulkAdmin').value));zp().forEach(x=>{x.planned=p;x.administered=a;x.status=a?'administered':p?'planned':'suggested'});render();save();toast('Valores aplicados a la zona.')};['vialUnits','dilutionMl'].forEach(id=>$(id).oninput=()=>{S.vial.units=num($('vialUnits').value);S.vial.dilution=num($('dilutionMl').value);summaries();table();save()});['productName','batchNumber','patientName','patientId','procedureDate'].forEach(id=>$(id).oninput=()=>{save();render()});['btnSave','btnSaveTop'].forEach(id=>$(id).onclick=()=>save(true));['btnPrint','btnPrintTop'].forEach(id=>$(id).onclick=()=>{save();print()});$('btnNew').onclick=()=>{if(confirm('¿Iniciar un nuevo procedimiento?')){let p=S.patient;S={...S,patient:p,points:presets(),selectedPointId:null,selectedZone:'glabella',visibleZone:null,zoom:1,showLabels:true,addMode:false};sessionStorage.removeItem(KEY);render()}};document.querySelectorAll('[data-mobile-tab]').forEach(b=>b.onclick=()=>mobile(b.dataset.mobileTab));addEventListener('message',e=>{if(e.source!==parent)return;let m=e.data||{};if(m.type==='ORION_DOCUMENTO_PACIENTE_SYNC'||m.type==='ORION_RECETA_PACIENTE_SYNC')patient(m.payload)});
render();mobile(S.mobileTab||'map');setTimeout(requestPatient,180);
})();
