var STORAGE_KEY="ordenautas_state";
var MAX_PARTICIPANTS=6;
var AVATARS=["🧑‍🚀","👩‍🚀","🤖","🦊","🐼","🦁","🐲","🦄","🦸","🥷","👾","🚀"];
var COLORS=["#183f5d","#a6548a","#2f7b63","#a35d2d","#6a58a9","#367a91"];
var DEFAULT_MISSIONS=[
{id:"shoes",icon:"👟",name:"Zapatos ordenados",points:1,cat:"Orden",team:0,quick:true},{id:"trash",icon:"🗑️",name:"Recoger mi basura",points:1,cat:"Orden",team:0,quick:true},{id:"toys",icon:"🧸",name:"Guardar juguetes",points:2,cat:"Orden",team:0,quick:true},{id:"desk",icon:"🧹",name:"Ordenar escritorio",points:2,cat:"Orden",team:0,quick:true},{id:"backpack",icon:"🎒",name:"Preparar mochila",points:2,cat:"Responsabilidad",team:0,quick:false},{id:"pets",icon:"🐾",name:"Alimentar mascotas",points:2,cat:"Mascotas",team:0,quick:false},{id:"read",icon:"📚",name:"Leer 20 minutos",points:3,cat:"Estudios",team:0,quick:false},{id:"study",icon:"✏️",name:"Estudiar 20 minutos",points:3,cat:"Estudios",team:0,quick:false},{id:"help",icon:"🤝",name:"Ayuda espontánea",points:3,cat:"Cooperación",team:0,quick:false},{id:"room",icon:"🛏️",name:"Ordenar habitación",points:5,cat:"Orden",team:0,quick:false},{id:"team",icon:"🛸",name:"Misión de la base",points:3,cat:"Cooperación",team:3,quick:false},{id:"noreminder",icon:"⚡",name:"Sin recordatorio",points:1,cat:"Bonificación",team:0,quick:false}
];
var DEFAULT_REWARDS=[
{id:"music",icon:"🎵",name:"Elegir la música",cost:5,type:"Privilegio"},{id:"dessert",icon:"🍨",name:"Postre especial",cost:8,type:"Comida"},{id:"games",icon:"🎮",name:"30 min videojuegos",cost:12,type:"Pantallas"},{id:"movie",icon:"🎬",name:"Elegir película",cost:15,type:"Panorama"},{id:"dadgame",icon:"🕹️",name:"Noche gamer con papá",cost:20,type:"Familiar"},{id:"food",icon:"🍔",name:"Comida especial",cost:25,type:"Comida"},{id:"icecream",icon:"🍦",name:"Salida por helado",cost:30,type:"Panorama"},{id:"cinema",icon:"🍿",name:"Ir al cine",cost:40,type:"Panorama"}
];
var DEFAULT_STATE={version:4,pin:"2026",activeParticipantId:"cristobal",teamPoints:0,participants:[{id:"cristobal",name:"Cristóbal",avatar:"🧑‍🚀",color:"#183f5d",available:0,historical:0,streak:0,archived:false},{id:"isidora",name:"Isidora",avatar:"👩‍🚀",color:"#a6548a",available:0,historical:0,streak:0,archived:false}],missions:DEFAULT_MISSIONS,rewards:DEFAULT_REWARDS,history:[],poster:{title:"BASE FAMILIAR",subtitle:"Pequeñas misiones. Grandes aventuras.",expedition:"Expedición a la montaña",target:45,showRules:true,showDate:true,participantIds:["cristobal","isidora"]}};
var LEVELS=[{name:"Cadete Ordenauta",min:0,max:29},{name:"Explorador Estelar",min:30,max:69},{name:"Guardián de la Base",min:70,max:119},{name:"Capitán de Misiones",min:120,max:199},{name:"Comandante Ordenauta",min:200,max:349},{name:"Leyenda Galáctica",min:350,max:999999}];
var state=loadState(),missionFilter="Todas",pendingRewardId=null,pendingParticipantId=null,toastTimer=null,deferredInstallPrompt=null,centralPanel="participants";
function $(s){return document.querySelector(s)}
function $$(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function clone(v){return JSON.parse(JSON.stringify(v))}
function safeNumber(v){var n=Number(v);return Number.isFinite(n)?n:0}
function cleanText(v,max){return String(v==null?"":v).trim().slice(0,max||80)}
function escapeHtml(v){return String(v==null?"":v).replace(/[&<>'"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]})}
function uniqueId(prefix){return prefix+"-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,7)}
function normalizeParticipant(raw,index){raw=raw&&typeof raw==="object"?raw:{};var fallbackAvatar=AVATARS[index%AVATARS.length],fallbackColor=COLORS[index%COLORS.length],avatar=cleanText(raw.avatar,8);return{id:cleanText(raw.id,60)||uniqueId("participant"),name:cleanText(raw.name,24)||("Ordenauta "+(index+1)),avatar:AVATARS.indexOf(avatar)>=0?avatar:fallbackAvatar,color:/^#[0-9a-fA-F]{6}$/.test(String(raw.color||""))?raw.color:fallbackColor,available:Math.max(0,safeNumber(raw.available)),historical:Math.max(0,safeNumber(raw.historical)),streak:Math.max(0,safeNumber(raw.streak)),archived:!!raw.archived}}
function normalizeMission(raw,index){raw=raw&&typeof raw==="object"?raw:{};return{id:cleanText(raw.id,60)||uniqueId("mission"),icon:cleanText(raw.icon,8)||"✅",name:cleanText(raw.name,45)||("Misión "+(index+1)),points:Math.max(1,Math.min(999,Math.round(safeNumber(raw.points)||1))),cat:cleanText(raw.cat,28)||"General",team:Math.max(0,Math.min(99,Math.round(safeNumber(raw.team)))),quick:typeof raw.quick==="boolean"?raw.quick:index<4}}
function normalizeReward(raw,index){raw=raw&&typeof raw==="object"?raw:{};return{id:cleanText(raw.id,60)||uniqueId("reward"),icon:cleanText(raw.icon,8)||"🎁",name:cleanText(raw.name,45)||("Recompensa "+(index+1)),cost:Math.max(1,Math.min(999,Math.round(safeNumber(raw.cost)||1))),type:cleanText(raw.type,28)||"Especial"}}
function loadState(){var saved=null;try{saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")}catch(e){saved=null}if(!saved||typeof saved!=="object")return clone(DEFAULT_STATE);var r=clone(DEFAULT_STATE);r.pin=/^\d{4,6}$/.test(String(saved.pin||""))?String(saved.pin):DEFAULT_STATE.pin;r.teamPoints=Math.max(0,safeNumber(saved.teamPoints));if(Array.isArray(saved.participants)&&saved.participants.length){r.participants=saved.participants.map(normalizeParticipant);r.activeParticipantId=cleanText(saved.activeParticipantId||saved.activePlayer,60)}else if(saved.players&&typeof saved.players==="object"){var legacy=[];Object.keys(saved.players).forEach(function(id,index){var p=saved.players[id]||{};legacy.push(normalizeParticipant({id:id,name:p.name,avatar:p.avatar||(index===0?"🧑‍🚀":"👩‍🚀"),color:p.color||COLORS[index%COLORS.length],available:p.available,historical:p.historical,streak:p.streak,archived:false},index))});if(legacy.length)r.participants=legacy.slice(0,MAX_PARTICIPANTS);r.activeParticipantId=cleanText(saved.activePlayer,60)}if(!r.participants.some(function(p){return !p.archived}))r.participants[0].archived=false;if(!r.participants.some(function(p){return p.id===r.activeParticipantId&&!p.archived}))r.activeParticipantId=r.participants.find(function(p){return !p.archived}).id;r.missions=(Array.isArray(saved.missions)&&saved.missions.length?saved.missions:DEFAULT_MISSIONS).map(normalizeMission);r.rewards=(Array.isArray(saved.rewards)&&saved.rewards.length?saved.rewards:DEFAULT_REWARDS).map(normalizeReward);r.history=Array.isArray(saved.history)?saved.history.slice(0,400):[];var sp=saved.poster&&typeof saved.poster==="object"?saved.poster:{};r.poster={title:cleanText(sp.title,50)||DEFAULT_STATE.poster.title,subtitle:cleanText(sp.subtitle,80)||DEFAULT_STATE.poster.subtitle,expedition:cleanText(sp.expedition,50)||DEFAULT_STATE.poster.expedition,target:Math.max(1,Math.min(999,Math.round(safeNumber(sp.target)||45))),showRules:sp.showRules!==false,showDate:sp.showDate!==false,participantIds:Array.isArray(sp.participantIds)?sp.participantIds.map(String):r.participants.filter(function(p){return !p.archived}).map(function(p){return p.id})};r.version=4;return r}
function saveState(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function now(){try{return new Date().toLocaleString("es-CL",{dateStyle:"short",timeStyle:"short"})}catch(e){return new Date().toLocaleString("es-CL")}}
function activeParticipants(){return state.participants.filter(function(p){return !p.archived})}
function currentParticipant(){return state.participants.find(function(p){return p.id===state.activeParticipantId&&!p.archived})||activeParticipants()[0]}
function findParticipant(id){return state.participants.find(function(p){return p.id===id})||null}
function findMission(id){return state.missions.find(function(x){return x.id===id})||null}
function findReward(id){return state.rewards.find(function(x){return x.id===id})||null}
function showToast(msg){var n=$("#toast");n.textContent=msg;n.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(function(){n.classList.remove("show")},2800)}
function setModalOpen(m,o){if(o){m.classList.add("open");document.body.classList.add("modal-open")}else{m.classList.remove("open");if(!$(".modal.open"))document.body.classList.remove("modal-open")}}
function addHistory(type,label,delta,who,meta){state.history.unshift({id:Date.now()+Math.random(),type:type,label:label,delta:delta,who:who,date:now(),meta:meta||{}});state.history=state.history.slice(0,400)}
function levelInfo(points){var idx=LEVELS.length-1;for(var i=0;i<LEVELS.length;i++){if(points>=LEVELS[i].min&&points<=LEVELS[i].max){idx=i;break}}var l=LEVELS[idx],next=LEVELS[Math.min(idx+1,LEVELS.length-1)],span=l.max-l.min+1,progress=idx===LEVELS.length-1?100:Math.max(0,Math.min(100,((points-l.min)/span)*100));return{index:idx,level:l,next:next,progress:progress}}
function completeMission(m){if(!m)return;var p=currentParticipant();p.available+=m.points;p.historical+=m.points;if(m.team)state.teamPoints+=m.team;addHistory("mission",m.name,m.points,p.id,{team:m.team||0,missionId:m.id});saveState();render();showToast("¡Misión completada! "+p.name+" ganó "+m.points+" punto"+(m.points===1?"":"s")+" de energía.")}
function requestReward(r){if(!r)return;var p=currentParticipant();if(p.available<r.cost){showToast("A "+p.name+" le faltan "+(r.cost-p.available)+" puntos para "+r.name+".");return}pendingRewardId=r.id;pendingParticipantId=p.id;$("#confirmTitle").textContent="Canjear: "+r.name;$("#confirmText").textContent="Se descontarán "+r.cost+" puntos de energía de "+p.name+".";$("#confirmPin").value="";setModalOpen($("#confirmModal"),true);setTimeout(function(){$("#confirmPin").focus()},120)}
function closeConfirm(){setModalOpen($("#confirmModal"),false);pendingRewardId=null;pendingParticipantId=null}
function confirmReward(){if($("#confirmPin").value!==state.pin){showToast("PIN incorrecto.");$("#confirmPin").select();return}var r=findReward(pendingRewardId),p=findParticipant(pendingParticipantId);if(!r||!p){showToast("No fue posible identificar el canje.");closeConfirm();return}if(p.available<r.cost){showToast("La energía disponible cambió y ya no alcanza.");closeConfirm();render();return}p.available-=r.cost;addHistory("reward",r.name,-r.cost,p.id,{rewardId:r.id});saveState();closeConfirm();render();showToast("¡Recompensa desbloqueada! "+r.name+".")}
function openParent(){$("#pinGate").style.display="block";$("#parentPanel").classList.remove("unlocked");$("#pinInput").value="";setModalOpen($("#parentModal"),true);setTimeout(function(){$("#pinInput").focus()},120)}
function closeParent(){setModalOpen($("#parentModal"),false)}
function unlockParent(){if($("#pinInput").value!==state.pin){showToast("PIN incorrecto.");$("#pinInput").select();return}$("#pinGate").style.display="none";$("#parentPanel").classList.add("unlocked");setCentralPanel(centralPanel);renderCentral()}
